services:
  - type: web
    name: collaborative-drawing-backend
    env: python
    region: singapore
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: collaborative-drawing-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: FRONTEND_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
